# Generated by Django 5.2.3 on 2025-06-25 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrativo', '0006_estudiante_tipo_matricula_costo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiante',
            name='tipo',
        ),
        migrations.AlterField(
            model_name='matricula',
            name='costo',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
